export const NAI_URL = 'https://novelai.net/image';
export const ID_ATTRIBUTE = 'data-projection-id';
export const BUTTON_TEXT_GENERATE_EN = 'Generate';
export const BUTTON_TEXT_GENERATE_JA = '生成';
export const BUTTON_TEXT_UPSCALE_EN = 'Upscale';
export const BUTTON_TEXT_UPSCALE_JA = '拡大';
export const BUTTON_ICON_SAVE = 'save';
export const BUTTON_ICON_VARIATIONS = 'variations';
export const BUTTON_ICON_UPSCALE = 'upscale';
export const BUTTON_TEXT_SEED_EN = 'Copy to Seed';
export const BUTTON_TEXT_SEED_JA = 'シード値をコピー';
export const BUTTON_TEXT_DELETE_HISTORY = 'Delete it!'; // 英語も日本語も同じ'
export const BUTTON_TEXT_IMPORT_IMAGE_EN = 'Import Image';
export const BUTTON_TEXT_IMPORT_IMAGE_JA = '画像をインポート';
export const DIV_TEXT_IMAGE_SETTINGS_EN = 'Image Settings';
export const DIV_TEXT_IMAGE_SETTINGS_JA = '画像設定';
export const BUTTON_TEXT_IMPORT_METADATA_EN = 'Import Metadata';
export const BUTTON_TEXT_IMPORT_METADATA_JA = 'メタデータをインポート';
