type ExtensionSettings = {
    generateEverywhere: boolean;
    datetimeFilename: boolean;
    enableDeleteHistoryWithoutConfirm: boolean;
    enableHistorySaveShortcut: boolean;
    hideModelSelector: boolean;
    hideDirectorTools: boolean;
    shrinkPromptArea: boolean;
    wheelHistory: boolean;
    highlightViewedHistory: boolean;
    confirmDialog: boolean;
    sliderButton: boolean;
    generatedSound: boolean;
    promptWidth: number;
    promptHeight: number;
    rearrangeImageSettings: boolean;
    shortcutControlBracket: boolean;
    shortcutAutoBracket: boolean;
    shortcutMoveLine: boolean;
    enablePromptFeature: boolean;
};
